#!/bin/bash

function createOrg1() {
  infoln "Enrolling the CA admin"
  mkdir -p crypto-config/peerOrganizations/org1.fedfab.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/

  fabric-ca-client enroll -u https://admin:adminpw@localhost:8050 --caname ca-org1 --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8050-ca-org1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8050-ca-org1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8050-ca-org1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8050-ca-org1.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/msp/tlscacerts"
  cp "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/msp/tlscacerts/ca.crt"

  # Copy org1's CA cert to org1's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/tlsca"
  cp "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/tlsca/tlsca.org1.fedfab.com-cert.pem"

  # Copy org1's CA cert to org1's /ca directory (for use by clients)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/ca"
  cp "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/ca/ca.org1.fedfab.com-cert.pem"

  infoln "Registering peer0"
  fabric-ca-client register --caname ca-org1 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  infoln "Registering peer1"
  fabric-ca-client register --caname ca-org1 --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  infoln "Registering peer2"
  fabric-ca-client register --caname ca-org1 --id.name peer2 --id.secret peer2pw --id.type peer --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  infoln "Registering user"
  fabric-ca-client register --caname ca-org1 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  infoln "Registering the org admin"
  fabric-ca-client register --caname ca-org1 --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  infoln "Generating the peer0 msp"
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8050 --caname ca-org1 -M "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/msp" --csr.hosts peer0.org1.fedfab.com --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/msp/config.yaml"

  infoln "Generating the peer1 msp"
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8050 --caname ca-org1 -M "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/msp" --csr.hosts peer1.org1.fedfab.com --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/msp/config.yaml"

  infoln "Generating the peer2 msp"
  fabric-ca-client enroll -u https://peer2:peer2pw@localhost:8050 --caname ca-org1 -M "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/msp" --csr.hosts peer2.org1.fedfab.com --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/msp/config.yaml"


  infoln "Generating the peer0-tls certificates"
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8050 --caname ca-org1 -M "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/tls" --enrollment.profile tls --csr.hosts peer0.org1.fedfab.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  infoln "Generating the peer1-tls certificates"
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8050 --caname ca-org1 -M "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/tls" --enrollment.profile tls --csr.hosts peer1.org1.fedfab.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  infoln "Generating the peer2-tls certificates"
  fabric-ca-client enroll -u https://peer2:peer2pw@localhost:8050 --caname ca-org1 -M "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/tls" --enrollment.profile tls --csr.hosts peer2.org1.fedfab.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/tls/tlscacerts/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/tls/ca.crt"
  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/tls/signcerts/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/tls/server.crt"
  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/tls/keystore/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer0.org1.fedfab.com/tls/server.key"

  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/tls/tlscacerts/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/tls/ca.crt"
  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/tls/signcerts/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/tls/server.crt"
  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/tls/keystore/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer1.org1.fedfab.com/tls/server.key"

  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/tls/tlscacerts/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/tls/ca.crt"
  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/tls/signcerts/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/tls/server.crt"
  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/tls/keystore/"* "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/peers/peer2.org1.fedfab.com/tls/server.key"

  infoln "Generating the user msp"
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8050 --caname ca-org1 -M "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/users/User1@org1.fedfab.com/msp" --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/users/User1@org1.fedfab.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:8050 --caname ca-org1 -M "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/users/Admin@org1.fedfab.com/msp" --tls.certfiles "${PWD}/crypto-config/fabric-ca/org1/ca-cert.pem"

  cp "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/org1.fedfab.com/users/Admin@org1.fedfab.com/msp/config.yaml"
}

function createOrg2() {
  infoln "Enrolling the CA admin"
  mkdir -p crypto-config/peerOrganizations/org2.fedfab.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/

  fabric-ca-client enroll -u https://admin:adminpw@localhost:9050 --caname ca-org2 --tls.certfiles "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem"

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9050-ca-org2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9050-ca-org2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9050-ca-org2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9050-ca-org2.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org2's CA cert to org2's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/msp/tlscacerts"
  cp "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/msp/tlscacerts/ca.crt"

  # Copy org2's CA cert to org2's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/tlsca"
  cp "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/tlsca/tlsca.org2.fedfab.com-cert.pem"

  # Copy org2's CA cert to org2's /ca directory (for use by clients)
  mkdir -p "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/ca"
  cp "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem" "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/ca/ca.org2.fedfab.com-cert.pem"

  infoln "Registering peer0"
  fabric-ca-client register --caname ca-org2 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem"

  infoln "Registering user"
  fabric-ca-client register --caname ca-org2 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem"

  infoln "Registering the org admin"
  fabric-ca-client register --caname ca-org2 --id.name org2admin --id.secret org2adminpw --id.type admin --tls.certfiles "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem"

  infoln "Generating the peer0 msp"
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9050 --caname ca-org2 -M "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/msp" --csr.hosts peer0.org2.fedfab.com --tls.certfiles "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem"

  cp "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9050 --caname ca-org2 -M "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/tls" --enrollment.profile tls --csr.hosts peer0.org2.fedfab.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem"

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/tls/tlscacerts/"* "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/tls/ca.crt"
  cp "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/tls/signcerts/"* "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/tls/server.crt"
  cp "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/tls/keystore/"* "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/peers/peer0.org2.fedfab.com/tls/server.key"

  infoln "Generating the user msp"
  fabric-ca-client enroll -u https://user1:user1pw@localhost:9050 --caname ca-org2 -M "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/users/User1@org2.fedfab.com/msp" --tls.certfiles "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem"

  cp "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/users/User1@org2.fedfab.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  fabric-ca-client enroll -u https://org2admin:org2adminpw@localhost:9050 --caname ca-org2 -M "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/users/Admin@org2.fedfab.com/msp" --tls.certfiles "${PWD}/crypto-config/fabric-ca/org2/ca-cert.pem"

  cp "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/msp/config.yaml" "${PWD}/crypto-config/peerOrganizations/org2.fedfab.com/users/Admin@org2.fedfab.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p crypto-config/ordererOrganizations/fedfab.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/crypto-config/ordererOrganizations/fedfab.com

  fabric-ca-client enroll -u https://admin:adminpw@localhost:7051 --caname ca-orderer --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7051-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7051-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7051-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7051-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/crypto-config/ordererOrganizations/fedfab.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/crypto-config/ordererOrganizations/fedfab.com/msp/tlscacerts"
  cp "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/crypto-config/ordererOrganizations/fedfab.com/msp/tlscacerts/tlsca.fedfab.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/crypto-config/ordererOrganizations/fedfab.com/tlsca"
  cp "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/crypto-config/ordererOrganizations/fedfab.com/tlsca/tlsca.fedfab.com-cert.pem"

  infoln "Registering orderer"
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"

  infoln "Registering the orderer admin"
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"

  infoln "Generating the orderer msp"
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:7051 --caname ca-orderer -M "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/msp" --csr.hosts orderer.fedfab.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"

  cp "${PWD}/crypto-config/ordererOrganizations/fedfab.com/msp/config.yaml" "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:7051 --caname ca-orderer -M "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/tls" --enrollment.profile tls --csr.hosts orderer.fedfab.com --csr.hosts localhost --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/tls/tlscacerts/"* "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/tls/ca.crt"
  cp "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/tls/signcerts/"* "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/tls/server.crt"
  cp "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/tls/keystore/"* "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/msp/tlscacerts"
  cp "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/tls/tlscacerts/"* "${PWD}/crypto-config/ordererOrganizations/fedfab.com/orderers/orderer.fedfab.com/msp/tlscacerts/tlsca.fedfab.com-cert.pem"

  infoln "Generating the admin msp"
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:7051 --caname ca-orderer -M "${PWD}/crypto-config/ordererOrganizations/fedfab.com/users/Admin@fedfab.com/msp" --tls.certfiles "${PWD}/crypto-config/fabric-ca/ordererOrg/ca-cert.pem"

  cp "${PWD}/crypto-config/ordererOrganizations/fedfab.com/msp/config.yaml" "${PWD}/crypto-config/ordererOrganizations/fedfab.com/users/Admin@fedfab.com/msp/config.yaml"
}
